#!/usr/bin/env node
import http from 'node:http'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { spawn, spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { VERSION, BUILD_ID, SOURCE_BASE, BEHAVIOR_REFERENCE } from './version.mjs'
const here=path.dirname(fileURLToPath(import.meta.url)); const args=process.argv.slice(2)
const arg=(n,f='')=>{const i=args.indexOf(n);return i>=0&&args[i+1]?args[i+1]:f}
const host=arg('--host','127.0.0.1'), port=Number(arg('--port','4173')), mode=arg('--mode','local')
const rootRaw=arg('--root',process.env.HOME||process.cwd()), root=mode==='local'?path.resolve(rootRaw):path.posix.normalize(rootRaw)
const label=arg('--label',mode==='remote'?'Remote workstation':'This Mac'), sshTarget=arg('--ssh-target',''), controlSocket=arg('--control-socket','')
const dist=path.join(here,'dist'), cacheRoot=arg('--cache',path.join(os.homedir(),'Library','Caches','Brainana Align',VERSION))
const allowed=['.nii','.nii.gz','.hdr','.img','.img.gz','.head','.brik','.brik.gz','.mgh','.mgz','.nrrd','.nhdr','.mif','.mha','.mhd','.raw','.v','.v16','.vmr','.npy','.npz','.fib','.src']
const isAllowed=n=>allowed.some(e=>String(n).toLowerCase().endsWith(e))
const cleanRel=rel=>{const clean=String(rel||'').replace(/^\/+/, '').split('/').filter(p=>p&&p!=='.').join('/');if(clean.split('/').includes('..'))throw Error('Path is outside the configured data root');return clean}
const safeLocal=rel=>{const clean=cleanRel(rel),resolved=path.resolve(root,clean);if(resolved!==root&&!resolved.startsWith(root+path.sep))throw Error('Path is outside the configured data root');return{clean,resolved}}
const safeRemote=rel=>{const clean=cleanRel(rel),resolved=path.posix.normalize(path.posix.join(root,clean));if(resolved!==root&&!resolved.startsWith(root.replace(/\/$/,'')+'/'))throw Error('Path is outside the configured data root');return{clean,resolved}}
const q=s=>"'"+String(s).replace(/'/g,"'\\''")+"'"
const sshArgs=()=>[...(controlSocket?['-S',controlSocket]:[]),'-o','BatchMode=yes','--',sshTarget]
const remoteCapture=(command)=>new Promise((resolve,reject)=>{const p=spawn('/usr/bin/ssh',[...sshArgs(),command],{stdio:['ignore','pipe','pipe']});let o='',e='';p.stdout.on('data',d=>o+=d);p.stderr.on('data',d=>e+=d);p.on('error',reject);p.on('close',c=>c===0?resolve(o):reject(Object.assign(Error(e.trim()||`SSH failed (${c})`),{code:c,stderr:e})))})
const sshConnected=()=>mode!=='remote'||spawnSync('/usr/bin/ssh',[...(controlSocket?['-S',controlSocket]:[]),'-O','check',sshTarget],{stdio:'ignore'}).status===0
const json=(res,s,obj)=>{const b=JSON.stringify(obj);res.writeHead(s,{'content-type':'application/json','content-length':Buffer.byteLength(b),'cache-control':'no-store'});res.end(b)}
const text=(res,s,msg)=>{res.writeHead(s,{'content-type':'text/plain; charset=utf-8','cache-control':'no-store'});res.end(msg)}
const readJson=async req=>{const a=[];for await(const c of req)a.push(c);return JSON.parse(Buffer.concat(a).toString()||'{}')}
async function list(rel,dirsOnly=false){
 if(mode==='local'){const {clean,resolved}=safeLocal(rel);const st=await fs.promises.stat(resolved);if(!st.isDirectory())throw Error('Not a directory');const ents=await fs.promises.readdir(resolved,{withFileTypes:true});const entries=[];for(const e of ents){if(e.name.startsWith('.')||(!e.isDirectory()&&(dirsOnly||!isAllowed(e.name))))continue;let size;if(e.isFile())size=(await fs.promises.stat(path.join(resolved,e.name))).size;entries.push({name:e.name,path:path.posix.join(clean,e.name),directory:e.isDirectory(),size})}entries.sort((a,b)=>Number(b.directory)-Number(a.directory)||a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'}));return{path:clean,parent:clean?(path.posix.dirname(clean)==='.'?'':path.posix.dirname(clean)):null,entries:dirsOnly?entries.filter(e=>e.directory):entries}}
 const {clean,resolved}=safeRemote(rel);const script=`test -d ${q(resolved)} && find ${q(resolved)} -mindepth 1 -maxdepth 1 -printf '%f\\t%y\\t%s\\n'`;const out=await remoteCapture(script);const entries=[];for(const line of out.split(/\r?\n/)){if(!line)continue;const [name,type,sizeRaw]=line.split('\t');if(!name||name.startsWith('.'))continue;const directory=type==='d';if(!directory&&(dirsOnly||!isAllowed(name)))continue;entries.push({name,path:path.posix.join(clean,name),directory,size:directory?undefined:Number(sizeRaw)})}entries.sort((a,b)=>Number(b.directory)-Number(a.directory)||a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'}));return{path:clean,parent:clean?(path.posix.dirname(clean)==='.'?'':path.posix.dirname(clean)):null,entries:dirsOnly?entries.filter(e=>e.directory):entries}
}
async function receiveTemp(req){await fs.promises.mkdir(cacheRoot,{recursive:true});const f=path.join(cacheRoot,`upload-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`);await new Promise((resolve,reject)=>{const w=fs.createWriteStream(f,{flags:'wx'});req.on('error',reject);w.on('error',reject);w.on('finish',resolve);req.pipe(w)});return f}
async function save(req,rel,overwrite){
 if(mode==='local'){const {clean,resolved}=safeLocal(rel);await fs.promises.mkdir(path.dirname(resolved),{recursive:true});if(!overwrite&&fs.existsSync(resolved)){const e=Error('File already exists');e.code='EEXIST';throw e}const tmp=resolved+`.brainana-part-${process.pid}-${Date.now()}`;await new Promise((resolve,reject)=>{const w=fs.createWriteStream(tmp,{flags:'wx'});req.on('error',reject);w.on('error',reject);w.on('finish',resolve);req.pipe(w)});if(overwrite)await fs.promises.rm(resolved,{force:true});await fs.promises.rename(tmp,resolved);return{path:clean,size:(await fs.promises.stat(resolved)).size}}
 const {clean,resolved}=safeRemote(rel);const local=await receiveTemp(req), remoteTmp=resolved+`.brainana-part-${process.pid}-${Date.now()}`;try{if(!overwrite){try{await remoteCapture(`test ! -e ${q(resolved)}`)}catch{const e=Error('File already exists');e.code='EEXIST';throw e}}await remoteCapture(`mkdir -p ${q(path.posix.dirname(resolved))}`);const scp=[...(controlSocket?['-o',`ControlPath=${controlSocket}`]:[]),'-q','--',local,`${sshTarget}:${remoteTmp}`];const c=spawnSync('/usr/bin/scp',scp,{stdio:'inherit'});if(c.status!==0)throw Error(`SCP failed (${c.status})`);await remoteCapture(`${overwrite?'rm -f '+q(resolved)+'; ':''}mv ${q(remoteTmp)} ${q(resolved)}`);return{path:clean,size:(await fs.promises.stat(local)).size}}finally{await fs.promises.rm(local,{force:true}).catch(()=>{});await remoteCapture(`rm -f ${q(remoteTmp)}`).catch(()=>{})}
}
const mime=p=>p.endsWith('.html')?'text/html; charset=utf-8':p.endsWith('.js')?'text/javascript; charset=utf-8':p.endsWith('.css')?'text/css; charset=utf-8':'application/octet-stream'
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost')
 if(u.pathname==='/api/health'){const connected=sshConnected();return json(res,connected?200:503,{ok:connected,app:'Brainana Align',version:VERSION,buildId:BUILD_ID,mode,connection:mode==='remote'?(connected?'ssh-connected':'ssh-disconnected'):'local'})}
 if(u.pathname==='/api/version')return json(res,200,{version:VERSION,buildId:BUILD_ID,sourceBase:SOURCE_BASE,behaviorReference:BEHAVIOR_REFERENCE})
 if(u.pathname==='/api/runtime')return json(res,200,{mode,label,root,port,host,version:VERSION,buildId:BUILD_ID,sshTarget:mode==='remote'?sshTarget:undefined,controlSocket:mode==='remote'?controlSocket:undefined,cacheRoot})
 if(u.pathname==='/api/config')return json(res,200,{enabled:true,mode,label,rootName:path.posix.basename(root)||root,remote:mode==='remote'})
 if(u.pathname==='/api/list')return json(res,200,await list(u.searchParams.get('path')||'',false))
 if(u.pathname==='/api/save-list')return json(res,200,await list(u.searchParams.get('path')||'',true))
 if(u.pathname==='/api/save-mkdir'&&req.method==='POST'){const b=await readJson(req);if(mode==='local'){const{clean,resolved}=safeLocal(b.path||'');await fs.promises.mkdir(resolved,{recursive:false});return json(res,200,{path:clean})}const{clean,resolved}=safeRemote(b.path||'');await remoteCapture(`mkdir ${q(resolved)}`);return json(res,200,{path:clean})}
 if(u.pathname==='/api/save-file'&&req.method==='POST'){try{return json(res,200,await save(req,u.searchParams.get('path')||'',u.searchParams.get('overwrite')==='1'))}catch(e){if(e.code==='EEXIST')return json(res,409,{error:'File already exists'});throw e}}
 if(u.pathname==='/api/file'){const rel=u.searchParams.get('path')||'';if(!isAllowed(rel))return text(res,415,'Unsupported file type');if(mode==='local'){const{resolved}=safeLocal(rel);const st=await fs.promises.stat(resolved);if(!st.isFile())return text(res,400,'Not a file');res.writeHead(200,{'content-type':'application/octet-stream','content-length':st.size,'content-disposition':`attachment; filename="${path.basename(resolved).replaceAll('"','')}"`});return fs.createReadStream(resolved).pipe(res)}const{resolved}=safeRemote(rel);const size=Number((await remoteCapture(`stat -c %s ${q(resolved)}`)).trim());res.writeHead(200,{'content-type':'application/octet-stream','content-length':size,'content-disposition':`attachment; filename="${path.posix.basename(resolved).replaceAll('"','')}"`});const p=spawn('/usr/bin/ssh',[...sshArgs(),`cat ${q(resolved)}`],{stdio:['ignore','pipe','pipe']});const stop=()=>{if(!p.killed)p.kill('SIGTERM')};req.on('aborted',stop);res.on('close',()=>{if(!res.writableEnded)stop()});p.stdout.pipe(res);p.stderr.on('data',d=>console.error(String(d)));return}
 let rel=decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname), file=path.resolve(dist,'.'+rel);if(file!==dist&&!file.startsWith(dist+path.sep))return text(res,403,'Forbidden');try{if((await fs.promises.stat(file)).isDirectory())file=path.join(file,'index.html')}catch{file=path.join(dist,'index.html')}const st=await fs.promises.stat(file);res.writeHead(200,{'content-type':mime(file),'content-length':st.size,'cache-control':file.endsWith('index.html')||file.includes('remote-export-')?'no-store':'public, max-age=31536000, immutable'});fs.createReadStream(file).pipe(res)
 }catch(e){console.error(e);json(res,500,{error:e instanceof Error?e.message:String(e)})}})
server.listen(port,host,()=>console.log(`Brainana Align ${VERSION} (${BUILD_ID}) ${mode} at http://${host}:${port}`))
