// GENERATED by scripts/generate-version.mjs — do not edit by hand.
export const APP_NAME = 'brainana-viewer'
export const APP_VERSION = "0.1.0"
export const BUILD_ID = "v0.1.0-2026-07-15"
export const versionInfo = Object.freeze({ app: APP_NAME, version: APP_VERSION, buildId: BUILD_ID })
