#!/usr/bin/env node
// Emits core/server/version.mjs — the single source of version + build id.
// Replaces the old triplicate hardcoding in server.mjs, launcher, and VERSION.json (finding R6).
// Version comes from package.json; buildId from the current git commit + date when available,
// falling back to a package-version stamp so the build is reproducible without git.
import { readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')

const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'))
const version = pkg.version

// Prefer a git tag/commit for the build id; degrade gracefully outside a git checkout.
function gitBuildId() {
  try {
    const sha = execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
    const tag = (() => {
      try {
        return execFileSync('git', ['describe', '--tags', '--always'], { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] })
          .toString()
          .trim()
      } catch {
        return sha
      }
    })()
    return `${tag}-${sha}`
  } catch {
    return null
  }
}

const date = new Date().toISOString().slice(0, 10) // YYYY-MM-DD
const buildId = process.env.BRAINANA_BUILD_ID || gitBuildId() || `v${version}-${date}`

const banner = '// GENERATED by scripts/generate-version.mjs — do not edit by hand.\n'
const body = `export const APP_NAME = 'brainana-viewer'
export const APP_VERSION = ${JSON.stringify(version)}
export const BUILD_ID = ${JSON.stringify(buildId)}
export const versionInfo = Object.freeze({ app: APP_NAME, version: APP_VERSION, buildId: BUILD_ID })
`

const dest = path.join(root, 'core', 'server', 'version.mjs')
writeFileSync(dest, banner + body)
console.log(`generate-version: wrote ${path.relative(root, dest)} (version ${version}, build ${buildId})`)
